name: Deploy to InfinityFree FTP host

on:
  push:
    branches:
      - maite/data
      - maite/main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'maite-deploy'
    steps:
      - uses: actions/checkout@v6
        with:
          ref: maite/main

      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Crear archivo .env desde secret
        run: |
          echo "${{ secrets.DOT_ENV }}" > .env
          echo "Archivo .env creado exitosamente"

      - name: Build web app
        run: pnpm build:front
        env:
          PUBLIC_SITE: ${{ vars.PUBLIC_SITE }}
          PUBLIC_BASE_URL: ${{ vars.PUBLIC_BASE_URL }}

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.INFINITY_SERVER }}
          username: ${{ secrets.INFINITY_USERNAME }}
          password: ${{ secrets.INFINITY_PASSWORD }}
          port: 21
          local-dir: packages/front/dist/
          server-dir: htdocs/
