name: Deploy to EvenNode

on:
  push:
    branches:
      - maite/data
      - maite/main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'maite-deploy'
    steps:
      - uses: actions/checkout@v6
        with:
          ref: maite/main

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: pnpm i

      - name: Crear archivo .env desde secret
        run: |
          echo "${{ secrets.DOT_ENV }}" > .env
          echo "Archivo .env creado exitosamente"

      - name: Build web app
        run: pnpm build

      - name: Clear sources
        run: rm -rf src public

      - name: Deploy to EvenNode
        uses: rodnye/evennode-deploy-action@v2
        with:
          key: ${{ secrets.EVENNODE_SSH_KEY }}
          git_url: ${{ secrets.EVENNODE_GIT_URL }}
          pre_commit_command: |
            git add .
            git add ./dist -f
